import { useEffect, useState, type FormEvent } from 'react'
import { Trash2, X } from 'lucide-react'
import type { NetworkConnection, NetworkDevice, RecordStatus } from '../types'
const statuses:RecordStatus[]=['Known','Needs Verification','Planned','Retired']
const fields:[keyof NetworkDevice,string,string?][]=[['hostname','Hostname'],['deviceType','Device type'],['manufacturer','Manufacturer'],['model','Model'],['managementIp','Management IP'],['subnetVlan','Subnet / VLAN'],['macAddress','MAC address'],['serialNumber','Serial number'],['connectionType','Connection type'],['physicalLocation','Physical location'],['switchPort','Switch port'],['lastVerified','Last verified','date']]
interface DeviceProps{kind:'device';value:NetworkDevice;onSave:(v:NetworkDevice)=>void;onDelete:()=>void;onClose:()=>void}
interface ConnectionProps{kind:'connection';value:NetworkConnection;deviceNames:Record<string,string>;onSave:(v:NetworkConnection)=>void;onDelete:()=>void;onClose:()=>void}
export function Drawer(props:DeviceProps|ConnectionProps){return <aside className="drawer" aria-label={`${props.kind} editor`}><div className="drawer-header"><div><span className="eyebrow">{props.kind} editor</span><h2>{props.value.id.startsWith('new-')?'New ':''}{props.kind}</h2></div><button className="icon-button" onClick={props.onClose} aria-label="Close editor"><X/></button></div>{props.kind==='device'?<DeviceForm {...props}/>:<ConnectionForm {...props}/>}</aside>}
function DeviceForm({value,onSave,onDelete}:DeviceProps){const [draft,setDraft]=useState(value);useEffect(()=>setDraft(value),[value]);const submit=(e:FormEvent)=>{e.preventDefault();onSave(draft)};return <form onSubmit={submit} className="editor-form"><div className="form-grid">{fields.map(([key,label,type])=><label key={key} className={key==='hostname'||key==='deviceType'?'span-2':''}><span>{label}</span><input type={type||'text'} value={String(draft[key])} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<label><span>Status</span><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as RecordStatus})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label><span>Infrastructure state</span><select value={draft.state} onChange={e=>setDraft({...draft,state:e.target.value as 'Current'|'Future'})}><option>Current</option><option>Future</option></select></label><label className="span-2"><span>Notes</span><textarea rows={5} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label></div><div className="form-actions"><button type="submit" className="primary">Save device</button><button type="button" className="danger" onClick={onDelete}><Trash2 size={16}/> Remove</button></div></form>}
function ConnectionForm({value,deviceNames,onSave,onDelete}:ConnectionProps){const [draft,setDraft]=useState(value);useEffect(()=>setDraft(value),[value]);return <form className="editor-form" onSubmit={e=>{e.preventDefault();onSave(draft)}}><div className="form-grid"><label className="span-2"><span>Label</span><input value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})}/></label><label><span>From</span><select value={draft.source} onChange={e=>setDraft({...draft,source:e.target.value})}>{Object.entries(deviceNames).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><label><span>To</span><select value={draft.target} onChange={e=>setDraft({...draft,target:e.target.value})}>{Object.entries(deviceNames).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><label className="span-2"><span>Connection type</span><input value={draft.connectionType} onChange={e=>setDraft({...draft,connectionType:e.target.value})}/></label><label><span>Status</span><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as RecordStatus})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label><span>Infrastructure state</span><select value={draft.state} onChange={e=>setDraft({...draft,state:e.target.value as 'Current'|'Future'})}><option>Current</option><option>Future</option></select></label></div><div className="form-actions"><button className="primary">Save connection</button><button type="button" className="danger" onClick={onDelete}><Trash2 size={16}/> Remove</button></div></form>}
