import type { Site } from '../types'
import { StatusBadge } from './Registers'
export function ManagementReport({site}:{site:Site}){const current=site.devices.filter(d=>d.state==='Current'&&d.status!=='Retired');const unverified=site.devices.filter(d=>d.status==='Needs Verification');return <article className="report">
 <header className="report-header"><div><span className="report-kicker">Network Design Register · Internal IT</span><h1>Network infrastructure report</h1><p>{site.name} · {site.address||'Address to be recorded'}</p></div><div className="report-meta">Generated {new Date().toLocaleDateString('en-AU',{day:'numeric',month:'long',year:'numeric'})}<br/>Register version 1</div></header>
 <section className="report-intro"><h2>Executive summary</h2><p>{site.description}</p><div className="report-metrics"><div><b>{current.length}</b><span>Current assets</span></div><div><b>{unverified.length}</b><span>Require verification</span></div><div><b>{site.devices.filter(d=>d.state==='Future').length}</b><span>Planned components</span></div><div><b>{site.ipPlan.length}</b><span>Networks / VLANs</span></div></div></section>
 <section><h2>Current topology</h2><div className="report-topology">{current.length===0?<p>No current-state assets have been recorded.</p>:current.map((d,i)=><div className="report-node" key={d.id}><b>{d.hostname}</b><span>{d.deviceType}</span>{i<current.length-1&&<i>→</i>}</div>)}</div><p className="report-note">Public WAN addresses are intentionally excluded from this management report.</p></section>
 <section><h2>Asset summary</h2><table><thead><tr><th>Asset</th><th>Type</th><th>Make / model</th><th>Location</th><th>Status</th></tr></thead><tbody>{current.map(d=><tr key={d.id}><td>{d.hostname}</td><td>{d.deviceType}</td><td>{[d.manufacturer,d.model].filter(Boolean).join(' · ')||'Not recorded'}</td><td>{d.physicalLocation||'Not recorded'}</td><td><StatusBadge status={d.status}/></td></tr>)}</tbody></table></section>
 <section><h2>IP and subnet summary</h2><table><thead><tr><th>Network</th><th>CIDR</th><th>VLAN</th><th>Purpose</th><th>Status</th></tr></thead><tbody>{site.ipPlan.map(e=><tr key={e.id}><td>{e.name}</td><td>{e.cidr||'Not recorded'}</td><td>{e.vlanId||'Not recorded'}</td><td>{e.purpose}</td><td><StatusBadge status={e.status}/></td></tr>)}</tbody></table></section>
 <div className="report-columns"><section><h2>Unverified items</h2><ul>{unverified.length?unverified.map(d=><li key={d.id}><b>{d.hostname}:</b> {d.notes||'Configuration requires verification.'}</li>):<li>No unverified devices.</li>}{site.ipPlan.filter(e=>e.status==='Needs Verification').map(e=><li key={e.id}><b>{e.name}:</b> addressing details require verification.</li>)}</ul></section><section><h2>Key risks and gaps</h2><ul>{site.risks.map(r=><li key={r}>{r}</li>)}</ul></section></div>
 <section><h2>Planned improvements</h2><ol>{site.plannedImprovements.map(p=><li key={p}>{p}</li>)}</ol></section><footer>Network Design Register · Internal use only · Validate technical configuration before implementation.</footer>
 </article>}
